=== manekinekko/mitic-dop/trunk/src/tp1/xml/carnetDAdresse.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT carnetDAdresse (carteDeVisite+)>
<!ELEMENT carteDeVisite (prénom, nom, organisme, adresse, note?)>
<!ATTLIST carteDeVisite
	id ID #REQUIRED
>
<!ELEMENT prénom (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT organisme (#PCDATA)>
<!ELEMENT adresse (numéro, voie, ville)>
<!ELEMENT numéro (#PCDATA)>
<!ELEMENT voie (#PCDATA)>
<!ATTLIST voie
	type (rue | avenue | impasse | cours | square | boulevard | chemin | allée | quai | route | passage | place | rondPoint) "rue"
>
<!ELEMENT ville (#PCDATA)>
<!ATTLIST ville
	codepostal CDATA #IMPLIED
>
<!ELEMENT note (#PCDATA | clé)*>
<!ELEMENT clé (#PCDATA)>

=== manekinekko/mitic-dop/xml/carnetDAdresse.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE carnetDAdresse SYSTEM "carnetDAdresse.dtd">
<!-- Mon carnet d'adresses -->
<?xml-stylesheet type="text/xsl" href="nav.xslt"?>
<carnetDAdresse>
	<carteDeVisite id="i1">
		<prénom>Yves</prénom>
		<nom>Bekkers</nom>
		<organisme>IFSIC</organisme>
		<?nom2 param1 param2 param3?>
		<!-- Une adresse -->
		<adresse>
			<numéro>42</numéro>
			<voie type="avenue">général Leclerc</voie>
			<ville codepostal="35042">Rennes</ville>
		</adresse>
		<note>Enseigne <clé>XML</clé> au SEP de Rennes 1</note>
	</carteDeVisite>
	<carteDeVisite id="i2">
		<prénom>Roland</prénom>
		<nom>Bartold</nom>
		<organisme>Net Center</organisme>
		<adresse>
			<numéro>256</numéro>
			<voie type="boulevard">Martenot</voie>
			<ville codepostal="35000">Rennes</ville>
		</adresse>
	</carteDeVisite>
	<carteDeVisite id="i6">
		<prénom>Ronan</prénom>
		<nom>Grosjean</nom>
		<organisme>Lavie</organisme>
		<adresse>
			<numéro>256</numéro>
			<voie>Martenot</voie>
			<ville codepostal="35000">Rennes</ville>
		</adresse>
		<note>Commercial <clé>réseau</clé>
		</note>
	</carteDeVisite>
	<carteDeVisite id="i3">
		<prénom>Pierre</prénom>
		<nom>Letertre</nom>
		<organisme>Dcom</organisme>
		<adresse>
			<numéro>1 bis</numéro>
			<voie>Cetavelon</voie>
			<ville codepostal="56000">Vannes</ville>
		</adresse>
	</carteDeVisite>
	<carteDeVisite id="i4">
		<prénom>Pierre</prénom>
		<nom>Apollon</nom>
		<organisme>Renove</organisme>
		<adresse>
			<numéro>56</numéro>
			<voie type="impasse">Moreau</voie>
			<ville codepostal="56400">Redon</ville>
		</adresse>
		<note>Pense qu'il est sorti de la cuisse de <clé>Jupiter</clé>
		</note>
	</carteDeVisite>
	<carteDeVisite id="i5">
		<prénom>Jean</prénom>
		<nom>Bartold</nom>
		<organisme>Dcom</organisme>
		<adresse>
			<numéro>56</numéro>
			<voie type="boulevard">Leclerc</voie>
			<ville codepostal="29000">Brest</ville>
		</adresse>
	</carteDeVisite>
</carnetDAdresse>
